<h2 id="on-table-words">On Tables</h2>
<div id="on-table">
<? for($i=0;$i<3;$i++) {
    $entry = $this->unplayed[$i];
    echo '<div class="gamediv">
    <strong>Game ' . $this->escape($entry['id']) . '</strong> <br />
      <span class="pink">' . $this->escape($entry['sidea']) . '</span><br />'
      . $this->escape(substr($entry['sideaorg'], 0, 11)) . '<br />
      VS.<br /><span class="green">
      ' . $this->escape($entry['sideb']) . '</span><br />'
      . $this->escape(substr($entry['sideborg'], 0, 11)) . '
    
  </div>';
  } ?>
<? $entry = $this->unplayed[$i];
    echo '<div class="lastgamediv">
   <strong>Game ' . $this->escape($entry['id']) . '</strong> <br />
      <span class="pink">' . $this->escape($entry['sidea']) . '</span><br />'
      . $this->escape(substr($entry['sideaorg'], 0, 11)) . '<br />
      VS.<br /><span class="green">
      ' . $this->escape($entry['sideb']) . '</span><br />'
      . $this->escape(substr($entry['sideborg'], 0, 11)) . '
    
  </div>';?>
</div>
<h2 id="ondeck-words">On Deck</h2>
<div id="ondeck">
 <? for($i=4;$i<7;$i++) {
    $entry = $this->unplayed[$i];
    echo '<div class="gamediv2">
    <strong>Game ' . $this->escape($entry['id']) . '</strong> <br />
      <span class="pink">' . $this->escape($entry['sidea']) . '</span><br />'
      . $this->escape(substr($entry['sideaorg'], 0, 11)) . '<br />
      VS.<br /><span class="green">
      ' . $this->escape($entry['sideb']) . '</span><br />'
      . $this->escape(substr($entry['sideborg'], 0, 11)) . '
    
  </div>';
  } ?>
  <? $entry = $this->unplayed[$i];
    echo '<div class="lastgamediv2">
    <strong>Game ' . $this->escape($entry['id']) . '</strong> <br />
      <span class="pink">' . $this->escape($entry['sidea']) . '</span><br />'
      . $this->escape(substr($entry['sideaorg'], 0, 11)) . '<br />
      VS.<br /><span class="green">
      ' . $this->escape($entry['sideb']) . '</span><br />'
      . $this->escape(substr($entry['sideborg'], 0, 11)) . '
    
  </div>'; ?>
</div>

<div id="next-div">
<h2>Next Up</h2>

<p><strong>Game Number</strong>:<br><strong>WHITE</strong> = Regular Game <br> <strong style="color:red">RED</strong> = Elimination Game</p>
<br />

<table class="game-table" id="next-up">
  <tr> 
<!--   <th></th> -->
   <th>Game </th> 
   <th>Pink Side  </th>  
   <th>Green Side  </th>
   <th>Win to</th> 
   <th>Loss to</th>
  </tr>

<?php 

for($i=8;$i<count($this->unplayed);$i++) {
  $entry = $this->unplayed[$i];

  /*consolation games will be made pink */
  echo 
  '<tr class="' . ($this->escape($entry['consolation'] > 0) ? 'cgame' : '') .  '" >' . 
  /*<!--  <td>( $this->escape($entry['consolation'] > 0) ? 'C' : '' ) ?><?= ( $this->escape($entry['final'] > 0) ? 'F' : '' )</td> --> */
    '<td>' . $this->escape($entry['id']) . '</td>
    <td style="background-color:#ff99ff;">' . $this->escape($entry['sidea']) . '<br> ' . $this->escape(substr($entry['sideaorg'], 0, 11)) . '</td>
    <td style="background-color:#99ff66;">' . $this->escape($entry['sideb']) . '<br> ' . $this->escape(substr($entry['sideborg'], 0, 11)) . '</td> 
    <td>' . $this->escape($entry['wgame']) . ' ' . $this->escape(str_replace(array('A', 'B'), array('P', 'G'), $entry['wside'])) . '</td>
    <td>' . (($entry['lgame'] > 0 ) ? $this->escape($entry['lgame']) . ' ' . $this->escape(str_replace(array('A', 'B'), array('P', 'G'), $entry['lside'])) : "") . '</td>
  </tr>';
}?>
</table>
</div>

<div id="completed-div">
  <h2>Completed</h2>

<p><strong>Game Number</strong>:<br><strong>WHITE</strong> = Regular Game <br> <strong style="color:red">RED</strong> = Elimination Game</p>
<br />

<table class="game-table" id="completed">
  <tr>
    <!--<th></th>-->
    <th>Game</th> <th>Pink Side</th> <th>Green Side</th> 
    <th>Victor</th> <!--<th>Win to</th> <th>Loss to</th>-->
  </tr>
 <?php foreach ($this->played as $entry) {
  /* If this game was a bye, which is automatically resolved, then do not display it */
    if ($this->escape($entry['sidea']) !== 'bye' && $this->escape($entry['sideb']) !== 'bye') {
      echo '<tr class="' . ($this->escape($entry['consolation']) ? 'cgame' : '') . '">' . 
      /*<!--<td><?= $this->escape($entry['round']) ?> <?= ( $this->escape($entry['consolation'] > 0) ? 'C' : '' ) ?><?= ( $this->escape($entry['final'] >0) ? 'F' : '' ) ?> --></td> */

      '<td>' . $this->escape($entry['id']) . '</td> 
      <td style="background-color:#ff99ff;">' . $this->escape($entry['sidea']) . '<br>' . $this->escape(substr($entry['sideaorg'], 0, 12)) . '</td> 
      <td style="background-color:#99ff66;">' . $this->escape($entry['sideb']) . '<br>' . $this->escape(substr($entry['sideborg'], 0, 12)) . '</td> 
      <td class="victor">' . $this->escape($entry['victor']) . '</td>' . 
      /*<!--  <td><?= $this->escape($entry['wgame']) ?> <?= $this->escape($entry['wside']) ?></td> 
      <td><?= ($entry['lgame'] > 0 ) ? $this->escape($entry['lgame']).'' . $this->escape($entry['lside']) : "" ?> </td> --> */
      '</tr>';
    }
  } ?>  
</table>

</div>

   <br style="clear:both;">



