

<div style="float:left;">
<h2>Next Up</h2>

<table class="game-table" id="next-up">
  <tr> 
   <th>Game</th> 
   <th>Pink Side </th>  
   <th>Green Side </th>
  <th>Win to</th> 
   <th>Loss to</th>
  </tr>



 <? foreach ($this->unplayed as $entry): ?>

<!-- consolation games will be made pink -->
  <tr class="<?=( $this->escape($entry['consolation'] > 0) ? 'cgame' : '' ) ?>">
  <!--  <td><?= ( $this->escape($entry['consolation'] > 0) ? 'C' : '' ) ?><?= ( $this->escape($entry['final'] > 0) ? 'F' : '' ) ?></td> -->
    <td><a href="<?= $this->baseUrl(); ?>/games/score?game=<?= $entry['id'] ?>"><?= $this->escape($entry['id']) ?></a></td> 
   <td style="background-color:#ff99ff;"><?= $this->escape($entry['sidea'])  ?><br> <?= $this->escape(substr($entry['sideaorg'], 0, 6)) ?> </td> 
    <td style="background-color:#99ff66;"><?= $this->escape($entry['sideb']) ?><br> <?= $this->escape(substr($entry['sideborg'], 0, 6)) ?> </td> 
    <td><?= $this->escape($entry['wgame']) ?> <?= $this->escape(str_replace(array('A', 'B'), array('P', 'G'), $entry['wside'])) ?></td> 
    <td><?= ($entry['lgame'] > 0 ) ? $this->escape($entry['lgame']).' ' . $this->escape(str_replace(array('A', 'B'), array('P', 'G'), $entry['lside'])) : "" ?> </td> 
  </tr>
<? endforeach ?>  
</table>

</div>

<div style="float:left; margin-left:1em">
  <h2>Completed</h2>

<table class="game-table">
  <tr> 
    <th>Round</th>
    <th>Game</th> <th>Pink Side</th> <th>Teal Side</th> 
    <th>Victor</th> <th>Win to</th> <th>Loss to</th>
  </tr>
 <? foreach ($this->played as $entry): ?>
  <tr>

   <td><?= $this->escape($entry['round']) ?> <?= ( $this->escape($entry['consolation'] > 0) ? 'C' : '' ) ?><?= ( $this->escape($entry['final'] > 0) ? 'F' : '' ) ?>
</td> 
   <td><a href="<?= $this->baseUrl(); ?>/games/score?game=<?= $entry['id'] ?>"><?= $this->escape($entry['id']) ?></a></td> 
    <td style="background-color:#ff99ff;"><?= $this->escape($entry['sidea'])  ?><br> <?= $this->escape(substr($entry['sideaorg'], 0, 12)) ?></td> 
    <td style="background-color:#99ff66;"><?= $this->escape($entry['sideb']) ?><br> <?= $this->escape(substr($entry['sideborg'], 0, 12)) ?></td> 
    <td class="victor"><?= $this->escape($entry['victor']) ?></td> 
    <td><?= $this->escape($entry['wgame']) ?> <?= $this->escape(str_replace(array('A', 'B'), array('P', 'G'), $entry['wside'])) ?></td> 
   <td><?= ($entry['lgame'] > 0 ) ? $this->escape($entry['lgame']).' ' . $this->escape(str_replace(array('A', 'B'), array('P', 'G'), $entry['lside'])) : "" ?> </td> 
  </tr>
<? endforeach ?>  
</table>

</div>

   <br style="clear:both;">

<h2>Games Admin</h2>

<ul>
  <li><a href="<?=$this->baseUrl()?>/bracket/build">Build games for DE bracket.</a></li>
</ul>


