<script language="JavaScript1.2">


/*
Advanced window scroller script-
By JavaScript Kit (www.javascriptkit.com)
Over 200+ free JavaScripts here!
*/

var currentpos=0,alt=1,curpos1=0,curpos2=-1,scrollTimer
function initialize(){
setTimeout("startit()", 2500)
}
function scrollwindow(){
if (document.all)
temp=document.body.scrollTop
else
temp=window.pageYOffset
if (alt==0)
alt=1
else
alt=0
if (alt==0)
curpos1=temp
else
curpos2=temp
if (curpos1!=curpos2){
if (document.all)
currentpos=document.body.scrollTop+1
else
currentpos=window.pageYOffset+1
window.scroll(0,currentpos)
}
else{
currentpos=0
setTimeout("window.scroll(0,currentpos)", 2500)
stopit()
setTimeout("startit()", 5000);
}
}
function startit(){
scrollTimer = setInterval("scrollwindow()",100)
}
function stopit(){
clearInterval(scrollTimer)
}

window.onload=initialize
</script>


<h2>Main Bracket </h2>
<p class="noprint">( <a href="<?= $this->baseUrl();?>/bracket/consolation">Click for consolation bracket.</a>) </p>  
<p class="noprint">( <a href="<?= $this->baseUrl();?>/bracket/finals">Click for finals bracket.</a>) </p>  
<div class="bracket" id="winners">

<?  $round=1; // always sart with round 1 ?> 
<div class="round phase-0" id="r1">
<? foreach ($this->wgames as $game): ?>

<?
   if( ( $game->round >$round) || ($game->final != 0) ) {
  $round++;
  echo "</div>";
  echo "<div class=\"round phase-0\" id=\"r".$round."\">";
} 
?>

<div class="game">
   <? // prepend a quote before hacking off the back so substr won't return flase for games where  sidea or  sideb = "bye" ?>

   <div class="team-a"> <div class="team-name"><?= $this->escape(     substr( " ".$game['sidea'], -4)     );?>  <?= $this->escape( substr($game['sideaorg'], 0, 6) );?> </div></div>
   <div class="team-b"> <div class="team-name"><?= $this->escape(     substr( " ".$game['sideb'], -4)     ) ;?>  <?= $this->escape( substr($game['sideborg'], 0, 6) );?> </div></div>
   <div class="game-number"><?= $this->escape($game['id']); ?></div> 
</div>

<? endforeach ?> 
</div> <!-- end of the last round div -->

<?  echo "<div class=\"round phase-0\" id=\"r". ($round+1) ."\">"; ?>
<div class="game">
   <div class="team-a"> 
   <div class="team-name">
   <?= $this->escape(     substr( " ".$game['victor'], -4)     );?> 
   </div> 
   </div>
</div>


</div> <!-- end of bracket -->
