<?= $this->doctype() ?> <!-- Doctype  set inside the bootstrap file -->
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
  <?php /* Editing out the auto-refresh on the admin side, as it gets annoying when entering special awards and other items.
  <meta http-equiv="Refresh" CONTENT="30">*/ ?>

  <title>Botball Tournament</title>

     <?= $this->headLink()->appendStylesheet($this->baseUrl().'/css/global.css', 'all') 
     ->prependStylesheet($this->baseUrl().'/css/bracket.css', 'all') 
     ->prependStylesheet($this->baseUrl().'/css/print.css', 'print'); ?>

  <?php echo '<link rel="apple-touch-icon" sizes="57x57" href="' . $this->baseUrl() . '/../data/uploads/imgs/apple-touch-icon-57x57.png">';
  echo '<link rel="apple-touch-icon" sizes="114x114" href="' . $this->baseUrl() . '/../data/uploads/imgs/apple-touch-icon-114x114.png">';
  echo '<link rel="apple-touch-icon" sizes="72x72" href="' . $this->baseUrl() . '/../data/uploads/imgs/apple-touch-icon-72x72.png">';
  echo '<link rel="apple-touch-icon" sizes="144x144" href="' . $this->baseUrl() . '/../data/uploads/imgs/apple-touch-icon-144x144.png">';
  echo '<link rel="apple-touch-icon" sizes="60x60" href="' . $this->baseUrl() . '/../data/uploads/imgs/apple-touch-icon-60x60.png">';
  echo '<link rel="apple-touch-icon" sizes="120x120" href="' . $this->baseUrl() . '/../data/uploads/imgs/apple-touch-icon-120x120.png">';
  echo '<link rel="apple-touch-icon" sizes="76x76" href="' . $this->baseUrl() . '/../data/uploads/imgs/apple-touch-icon-76x76.png">';
  echo '<link rel="apple-touch-icon" sizes="152x152" href="' . $this->baseUrl() . '/../data/uploads/imgs/apple-touch-icon-152x152.png">';
  echo '<link rel="icon" type="image/png" href="' . $this->baseUrl() . '/../data/uploads/imgs/favicon-196x196.png" sizes="196x196">';
  echo '<link rel="icon" type="image/png" href="' . $this->baseUrl() . '/../data/uploads/imgs/favicon-160x160.png" sizes="160x160">';
  echo '<link rel="icon" type="image/png" href="' . $this->baseUrl() . '/../data/uploads/imgs/favicon-96x96.png" sizes="96x96">';
  echo '<link rel="icon" type="image/png" href="' . $this->baseUrl() . '/../data/uploads/imgs/favicon-16x16.png" sizes="16x16">';
  echo '<link rel="icon" type="image/png" href="' . $this->baseUrl() . '/../data/uploads/imgs/favicon-32x32.png" sizes="32x32"> ';
  echo '<meta name="msapplica
  tion-TileColor" content="#2b5797">';
  echo '<meta name="msapplication-TileImage" content="' . $this->baseUrl() . '/../data/uploads/imgs/mstile-144x144.png">';
  ?>

</head> 
<body>

<div id="header">
	<h1><img src="../data/uploads/imgs/botball-logo.png" height="22"/> Oklahoma Regional Tournament</h1>
</div>

<div id="navmenu">
<ul>
<li> <a href="<?= $this->baseUrl(); ?>/teams/" id="teams">Teams</a></li>
<?php /*<li> <a href="<?= $this->baseUrl(); ?>/roster" id="roster">Seeding and Onsite</a></li> */ ?>
<li> <a href="<?= $this->baseUrl(); ?>/games" id="games">DE Games</a></li>
<li> <a href="<?= $this->baseUrl(); ?>/bracket" id="bracket">DE Bracket</a></li>
<li> <a href="<?= $this->baseUrl(); ?>/awards" id="awards">Special Awards</a></li>
<li> <a href="<?= $this->baseUrl(); ?>/roster/awards" id="results">Tournament Results</a></li>
<li> <a href="<?= $this->baseUrl(); ?>/roster/awards" id="results">Start New Tournament</a></li>
</ul>
</div>


<?= $this->layout()->content ?>


<div id="footer">
</div>

</body>
</html>
