
<h3>Teams Admin</h3>
<ul>
  <li><a href="<?= $this->baseUrl();?>/roster/upload">Import teams for a new tournament</a></li>
  <li><a href="<?= $this->baseUrl();?>/teams/add">Add a team to the tournament roster</a></li>
</ul>

<table class="results">

<tr>
<th>Team Code</th>
<th>Organization</th>
<?php /*<th>email</th>*/ ?>

<th>P1 Doc</th>
<th>P2 Doc</th>
<th>P3 Doc</th>
<th>Onsite</th>

<th>S1</th>
<th>S2</th>
<th>S3</th>
<th>Seed Avg</th> 
<th>Seed Rank</th>

</tr>
 <!-- Loop through the entries that were provided to us by the controller -->
 <?php foreach ($this->teams as $team) {
  $code = $this->escape($team['code']);
  $roster = new Roster();
  $entry = $roster->fetchRow($roster->select()->where('code = ?', $code));

  echo '<tr>

  <td style="text-align:left;">' . $this->escape($team['code']) . '</td> 
  <td style="text-align:left;"><a href="' . $this->baseUrl() . '/teams/edit?code=' . $team['code'] . '" >' . $this->escape($team['org']) . '</a></td>' . 
  /*<td style="text-align:left;"><?= $this->escape($team['email']) ?></td>*/

  '<td>' . $this->escape($team['p1doc']) . '</td>
  <td>' . $this->escape($team['p2doc']) . '</td>
  <td>' . $this->escape($team['p3doc']) . '</td>
  <td>' . $this->escape($team['p4doc']) . '</td>

  <td>' . $this->escape($team['seed1']) . '</td>
  <td>' . $this->escape($team['seed2']) . '</td>
  <td>' . $this->escape($team['seed3']) . '</td>
  <td>' . $this->escape($entry['seedavg']) . '</td>
  <td>' . $this->escape($entry['seedrank']) . '</td>'
  ;}?> 
</table>